# Generated by Django 3.1.2 on 2020-11-20 04:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201119_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
