# Generated by Django 3.1.2 on 2020-11-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201122_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fourth_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='header_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='second_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='third_image',
        ),
    ]
