# Generated by Django 3.1.2 on 2020-11-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20201122_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
