# Generated by Django 3.1.2 on 2020-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
